import assert from 'node:assert/strict';
import { createStellarRpcAdapter, validateStellarRpcConfig, type OpaqueContractInvocation, type StellarRpcTransport } from '../api/_lib/stellar-testnet-rpc-adapter.ts';
import { TESTNET_PASSPHRASE, TESTNET_RPC, syntheticContractId } from '../api/_lib/simulated-testnet-adapter.ts';
const contractId = syntheticContractId(), wasm = 'a'.repeat(64);
const base = { mode: 'fixture' as const, networkPassphrase: TESTNET_PASSPHRASE, rpcUrl: TESTNET_RPC, allowedRpcUrls: [TESTNET_RPC], contractId, allowedContractIds: [contractId], wasmSha256: wasm, allowedWasmSha256: [wasm], submissionEnabled: true, timeoutMs: 5 };
const invocation: OpaqueContractInvocation = { operationId: 'operation_fixture_0001', receiptHandle: 'receipt_handle_fixture_0001', expectedVersion: 0, functionName: 'issue', commitment: 'b'.repeat(64) };
const signer = { async sign() { return { signedXdr: 'fixture-signed-xdr-no-secret', keyVersion: 3 }; } };
let submitCalls = 0;
const transport: StellarRpcTransport = { kind: 'fixture', async simulate() { return { status: 'ready', envelope: { xdr: 'fixture-unsigned-xdr', transactionHash: 'c'.repeat(64) } }; }, async submit(envelope) { submitCalls += 1; return { status: 'submitted', transactionHash: envelope.transactionHash, ledgerSequence: 50 }; }, async confirm(hash) { return { status: 'confirmed', transactionHash: hash, ledgerSequence: 52 }; } };
const adapter = createStellarRpcAdapter({ config: base, transport, signer });
assert.equal((await adapter.simulate(invocation)).state, 'simulated'); assert.equal((await adapter.sign(invocation.operationId)).state, 'signed');
assert.equal((await adapter.submit(invocation.operationId)).state, 'submitted'); assert.equal((await adapter.submit(invocation.operationId)).state, 'submitted'); assert.equal(submitCalls, 1);
assert.equal((await adapter.confirm(invocation.operationId)).state, 'confirmed');
assert.throws(() => adapter.prepare({ ...invocation, commitment: 'd'.repeat(64) }), (error: any) => error.code === 'IDEMPOTENCY_CONFLICT');
const testnetConfig = { ...base, mode: 'testnet' as const, submissionEnabled: false };
validateStellarRpcConfig(testnetConfig);
assert.throws(() => validateStellarRpcConfig({ ...testnetConfig, submissionEnabled: true }), (error: any) => error.code === 'TESTNET_SUBMISSION_GATE_CLOSED');
assert.throws(() => validateStellarRpcConfig({ ...testnetConfig, rpcUrl: 'https://evil.invalid' }), (error: any) => error.code === 'RPC_URL_ALLOWLIST_REJECTED');
const blocked = createStellarRpcAdapter({ config: testnetConfig, transport: { ...transport, kind: 'stellar-rpc' }, signer });
await blocked.simulate({ ...invocation, operationId: 'operation_fixture_0002' }); await blocked.sign('operation_fixture_0002');
await assert.rejects(() => blocked.submit('operation_fixture_0002'), (error: any) => error.code === 'SUBMISSION_GATE_CLOSED');
let timedSubmit = 0;
const timeoutTransport: StellarRpcTransport = { kind: 'fixture', async simulate() { return transport.simulate(invocation, 1); }, async submit() { timedSubmit += 1; return new Promise(() => undefined); }, async confirm(hash) { return { status: 'not_found', transactionHash: hash }; } };
const uncertain = createStellarRpcAdapter({ config: base, transport: timeoutTransport, signer });
await uncertain.simulate({ ...invocation, operationId: 'operation_fixture_0003' }); await uncertain.sign('operation_fixture_0003');
assert.equal((await uncertain.submit('operation_fixture_0003')).state, 'unknown'); assert.equal((await uncertain.submit('operation_fixture_0003')).state, 'unknown'); assert.equal(timedSubmit, 1);
console.log('stellar RPC preparation passed');
