import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import ts from 'typescript';
const source = await readFile(new URL('./guard.ts', import.meta.url), 'utf8');
const code = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
let transport = async () => Response.json({ ok: true });
const window = new EventTarget(); window.fetch = (...args) => transport(...args); window.open = () => null;
class XMLHttpRequest { open() {} send() {} setRequestHeader() {} }
const exports = {}, context = vm.createContext({ exports, window, location: { origin: 'http://127.0.0.1:4331' },
  URL, Headers, Request, Response, Event, CustomEvent, XMLHttpRequest, navigator: { serviceWorker: { register() {} }, sendBeacon() {} }, document: new EventTarget() });
vm.runInContext(code, context);
const metadata = number => ({ generation: number, access: `synthetic-${number}`, identities: [] });
const input = { method: 'POST', body: JSON.stringify({ action: 'receive', input: { operationId: 'synthetic-operation' } }) };
exports.configureDemo(metadata(1));
transport = async () => new Response('{broken', { status: 200, headers: { 'content-type': 'application/json' } });
await assert.rejects(window.fetch('/api/dispensary-commerce', input));
assert.equal(exports.hasPendingDemoWrite(), true, 'malformed 200 body retains uncertain operation');
transport = async () => Response.json({ resourceRef: 'synthetic-receipt' });
await window.fetch('/api/dispensary-commerce', input);
assert.equal(exports.hasPendingDemoWrite(), false, 'same command success clears uncertainty');
let release;
transport = () => new Promise((_, reject) => { release = reject; });
const old = window.fetch('/api/dispensary-commerce', input);
assert.equal(exports.hasPendingDemoWrite(), true);
exports.configureDemo(metadata(2));
assert.equal(exports.hasPendingDemoWrite(), false);
release(new Error('synthetic-late-abort')); await assert.rejects(old);
assert.equal(exports.hasPendingDemoWrite(), false, 'late old abort cannot repopulate new uncertainty');
let expiredEvents = 0; window.addEventListener('local-demo-expired', () => expiredEvents++);
transport = () => new Promise(resolve => { release = resolve; });
const oldRead = window.fetch('/api/operations-pilot');
exports.configureDemo(metadata(3));
release(Response.json({ code: 'LOCAL_CONTEXT_EXPIRED' }, { status: 409 }));
await assert.rejects(oldRead, /LOCAL_STALE_RESPONSE/);
assert.equal(expiredEvents, 0, 'old 409 cannot withdraw the new context');
let body, headersDelivered;
const headersReady = new Promise(resolve => { headersDelivered = resolve; });
transport = async () => {
  const response = new Response(new ReadableStream({ start(controller) { body = controller; } }), { headers: { 'content-type': 'application/json' } });
  headersDelivered();
  return response;
};
const reading = window.fetch('/api/dispensary-commerce', input);
await headersReady;
await Promise.resolve();
assert.equal(exports.hasPendingDemoWrite(), true, 'headers are not a complete acknowledgement');
body.enqueue(new TextEncoder().encode('{"resourceRef":"synthetic-buffered"}')); body.close();
const response = await reading; assert.equal((await response.json()).resourceRef, 'synthetic-buffered');
assert.equal(exports.hasPendingDemoWrite(), false);
let saved = 0; window.addEventListener('local-demo-saved', () => saved++);
transport = async () => Response.json({ ok: true });
for (const action of ['list', 'inspect', 'read-draft', 'grant']) await window.fetch('/api/dispensary-onboarding', { method: 'POST', body: JSON.stringify({ action }) });
assert.equal(saved, 0, 'reads and grants never clear unrelated drafts');
await window.fetch('/api/operations-pilot', { method: 'POST', body: JSON.stringify({ action: 'save-profile', input: {} }) });
assert.equal(saved, 1);
exports.invalidateDemoScope();
await assert.rejects(window.fetch('/api/operations-pilot'), /LOCAL_CONTEXT_EXPIRED/);
exports.configureDemo(metadata(4));
assert.equal(exports.hasPendingDemoWrite(), false);
console.log('PASS actual browser-guard source: malformed/pending JSON, exact retry, stale abort/409, scoped epochs, unrelated reads/grants, explicit expiration. No network.');
